framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            print:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    stream: print
                    group: print-workers
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            App\Message\ProcessPrintJob: print
            App\Message\RefreshPrintJobStatus: print

when@test:
    framework:
        messenger:
            transports:
                print:
                    dsn: 'in-memory://'
