<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates printer and print-job storage and completes trait-backed fields.
 */
final class Version20261007212342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Printer and PrintJob tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE print_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, report_date DATE DEFAULT NULL, external_job_id VARCHAR(255) DEFAULT NULL, attempt_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, printer_id INT NOT NULL, order_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_print_job_status ON print_job (status)');
        $this->addSql('CREATE INDEX idx_print_job_created_at ON print_job (created_at)');
        $this->addSql('CREATE INDEX idx_print_job_printer ON print_job (printer_id)');
        $this->addSql('CREATE INDEX idx_print_job_order ON print_job (order_id)');
        $this->addSql('CREATE TABLE printer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(2048) NOT NULL, for_labels BOOLEAN DEFAULT false NOT NULL, for_reports BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE print_job ADD CONSTRAINT FK_4FAA469B46EC494A FOREIGN KEY (printer_id) REFERENCES printer (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE print_job ADD CONSTRAINT FK_4FAA469B8D9F6D38 FOREIGN KEY (order_id) REFERENCES bakery_order (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bakery_order ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE bakery_order ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE customer ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE customer ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE customer ADD active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE employee ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE employee ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE employee ADD active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE product_type ADD active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE unit ADD active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE bakery_order ALTER COLUMN created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE bakery_order ALTER COLUMN updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE customer ALTER COLUMN created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE customer ALTER COLUMN updated_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE print_job DROP CONSTRAINT FK_4FAA469B46EC494A');
        $this->addSql('ALTER TABLE print_job DROP CONSTRAINT FK_4FAA469B8D9F6D38');
        $this->addSql('DROP TABLE print_job');
        $this->addSql('DROP TABLE printer');
        $this->addSql('ALTER TABLE bakery_order DROP created_at');
        $this->addSql('ALTER TABLE bakery_order DROP updated_at');
        $this->addSql('ALTER TABLE customer DROP created_at');
        $this->addSql('ALTER TABLE customer DROP updated_at');
        $this->addSql('ALTER TABLE customer DROP active');
        $this->addSql('ALTER TABLE employee DROP created_at');
        $this->addSql('ALTER TABLE employee DROP updated_at');
        $this->addSql('ALTER TABLE employee DROP active');
        $this->addSql('ALTER TABLE product_type DROP active');
        $this->addSql('ALTER TABLE unit DROP active');
    }
}
