<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the order and order-item domain tables.
 */
final class Version20261007211731 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Order and OrderItem tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bakery_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(50) NOT NULL, customer_name VARCHAR(255) NOT NULL, customer_phone VARCHAR(35) NOT NULL, pickup_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ordered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid BOOLEAN DEFAULT false NOT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, customer_id INT NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bakery_order_pickup_at ON bakery_order (pickup_at)');
        $this->addSql('CREATE INDEX idx_bakery_order_status ON bakery_order (status)');
        $this->addSql('CREATE INDEX idx_bakery_order_customer ON bakery_order (customer_id)');
        $this->addSql('CREATE INDEX idx_bakery_order_employee ON bakery_order (employee_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_bakery_order_order_number ON bakery_order (order_number)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(10, 2) NOT NULL, description TEXT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, order_id INT NOT NULL, product_type_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_order_item_order ON order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F0914959723 ON order_item (product_type_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F09F8BD700D ON order_item (unit_id)');
        $this->addSql('ALTER TABLE bakery_order ADD CONSTRAINT FK_48439BDE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bakery_order ADD CONSTRAINT FK_48439BDE8C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES bakery_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F0914959723 FOREIGN KEY (product_type_id) REFERENCES product_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE bakery_order DROP CONSTRAINT FK_48439BDE9395C3F3');
        $this->addSql('ALTER TABLE bakery_order DROP CONSTRAINT FK_48439BDE8C03F15C');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F0914959723');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09F8BD700D');
        $this->addSql('DROP TABLE bakery_order');
        $this->addSql('DROP TABLE order_item');
    }
}
