<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261008143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add package units, packaging rules, and package label metadata';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE unit ADD is_package_unit BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('CREATE TABLE packaging_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity_per_package NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, product_type_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_packaging_rule_product_unit ON packaging_rule (product_type_id, unit_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_packaging_rule_product_unit_active ON packaging_rule (product_type_id, unit_id, active) WHERE active = TRUE');
        $this->addSql('ALTER TABLE packaging_rule ADD CONSTRAINT FK_PACKAGING_RULE_PRODUCT_TYPE FOREIGN KEY (product_type_id) REFERENCES product_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE packaging_rule ADD CONSTRAINT FK_PACKAGING_RULE_UNIT FOREIGN KEY (unit_id) REFERENCES unit (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE print_job ADD order_item_id INT DEFAULT NULL, ADD package_number INT DEFAULT NULL, ADD package_count INT DEFAULT NULL, ADD package_quantity NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_print_job_order_item ON print_job (order_item_id)');
        $this->addSql('ALTER TABLE print_job ADD CONSTRAINT FK_PRINT_JOB_ORDER_ITEM FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE print_job DROP CONSTRAINT FK_PRINT_JOB_ORDER_ITEM');
        $this->addSql('DROP INDEX idx_print_job_order_item');
        $this->addSql('ALTER TABLE print_job DROP order_item_id, DROP package_number, DROP package_count, DROP package_quantity');
        $this->addSql('ALTER TABLE packaging_rule DROP CONSTRAINT FK_PACKAGING_RULE_PRODUCT_TYPE');
        $this->addSql('ALTER TABLE packaging_rule DROP CONSTRAINT FK_PACKAGING_RULE_UNIT');
        $this->addSql('DROP INDEX uniq_packaging_rule_product_unit_active');
        $this->addSql('DROP INDEX idx_packaging_rule_product_unit');
        $this->addSql('DROP TABLE packaging_rule');
        $this->addSql('ALTER TABLE unit DROP is_package_unit');
    }
}
