<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261008203339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migrations';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bakery_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(50) NOT NULL, customer_name VARCHAR(255) NOT NULL, customer_phone VARCHAR(35) NOT NULL, pickup_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ordered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid BOOLEAN DEFAULT false NOT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bakery_order_pickup_at ON bakery_order (pickup_at)');
        $this->addSql('CREATE INDEX idx_bakery_order_status ON bakery_order (status)');
        $this->addSql('CREATE INDEX idx_bakery_order_customer ON bakery_order (customer_id)');
        $this->addSql('CREATE INDEX idx_bakery_order_user ON bakery_order (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_bakery_order_order_number ON bakery_order (order_number)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(35) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_customer_phone ON customer (phone)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(10, 2) NOT NULL, description TEXT NOT NULL, sort_order INT DEFAULT 0 NOT NULL, order_id INT NOT NULL, product_type_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_order_item_order ON order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F0914959723 ON order_item (product_type_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F09F8BD700D ON order_item (unit_id)');
        $this->addSql('CREATE TABLE packaging_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity_per_package NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, product_type_id INT NOT NULL, unit_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_packaging_rule_product_unit ON packaging_rule (product_type_id, unit_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_packaging_rule_product_unit_active ON packaging_rule (product_type_id, unit_id, active) WHERE (active = true)');
        $this->addSql('CREATE INDEX IDX_1EAC7DFE14959723 ON packaging_rule (product_type_id)');
        $this->addSql('CREATE INDEX IDX_1EAC7DFEF8BD700D ON packaging_rule (unit_id)');
        $this->addSql('CREATE TABLE print_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, package_number INT DEFAULT NULL, package_count INT DEFAULT NULL, package_quantity NUMERIC(10, 2) DEFAULT NULL, report_date DATE DEFAULT NULL, external_job_id VARCHAR(255) DEFAULT NULL, document_path VARCHAR(2048) DEFAULT NULL, attempt_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, printer_id INT NOT NULL, order_id INT DEFAULT NULL, order_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_print_job_status ON print_job (status)');
        $this->addSql('CREATE INDEX idx_print_job_created_at ON print_job (created_at)');
        $this->addSql('CREATE INDEX idx_print_job_printer ON print_job (printer_id)');
        $this->addSql('CREATE INDEX idx_print_job_order ON print_job (order_id)');
        $this->addSql('CREATE INDEX idx_print_job_order_item ON print_job (order_item_id)');
        $this->addSql('CREATE TABLE printer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(2048) NOT NULL, for_labels BOOLEAN DEFAULT false NOT NULL, default_for_labels BOOLEAN DEFAULT false NOT NULL, for_reports BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_printer_default_for_labels ON printer (default_for_labels) WHERE (default_for_labels = true)');
        $this->addSql('CREATE TABLE product_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, abbreviation VARCHAR(50) DEFAULT NULL, package_unit BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(255) NOT NULL, roles JSON NOT NULL, sort_order INT DEFAULT 0 NOT NULL, password VARCHAR(255) DEFAULT NULL, employee BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql('ALTER TABLE bakery_order ADD CONSTRAINT FK_48439BDE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bakery_order ADD CONSTRAINT FK_48439BDEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES bakery_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F0914959723 FOREIGN KEY (product_type_id) REFERENCES product_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE packaging_rule ADD CONSTRAINT FK_1EAC7DFE14959723 FOREIGN KEY (product_type_id) REFERENCES product_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE packaging_rule ADD CONSTRAINT FK_1EAC7DFEF8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE print_job ADD CONSTRAINT FK_4FAA469B46EC494A FOREIGN KEY (printer_id) REFERENCES printer (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE print_job ADD CONSTRAINT FK_4FAA469B8D9F6D38 FOREIGN KEY (order_id) REFERENCES bakery_order (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE print_job ADD CONSTRAINT FK_4FAA469BE415FB15 FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bakery_order DROP CONSTRAINT FK_48439BDE9395C3F3');
        $this->addSql('ALTER TABLE bakery_order DROP CONSTRAINT FK_48439BDEA76ED395');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F0914959723');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09F8BD700D');
        $this->addSql('ALTER TABLE packaging_rule DROP CONSTRAINT FK_1EAC7DFE14959723');
        $this->addSql('ALTER TABLE packaging_rule DROP CONSTRAINT FK_1EAC7DFEF8BD700D');
        $this->addSql('ALTER TABLE print_job DROP CONSTRAINT FK_4FAA469B46EC494A');
        $this->addSql('ALTER TABLE print_job DROP CONSTRAINT FK_4FAA469B8D9F6D38');
        $this->addSql('ALTER TABLE print_job DROP CONSTRAINT FK_4FAA469BE415FB15');
        $this->addSql('DROP TABLE bakery_order');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE packaging_rule');
        $this->addSql('DROP TABLE print_job');
        $this->addSql('DROP TABLE printer');
        $this->addSql('DROP TABLE product_type');
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP TABLE users');
    }
}
